# Generated by Django 5.0.2 on 2024-03-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('F', 'favorite'), ('P', 'Personal'), ('S', 'Social'), ('Sp', 'Sport'), ('W', 'Weather'), ('H', 'Health'), ('Wk', 'Work'), ('R', 'Research')], max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
