# Generated by Django 5.0.2 on 2024-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_app', '0004_alter_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
