# Generated by Django 5.0.2 on 2024-02-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_app', '0011_alter_liked_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='apple_app.product'),
        ),
    ]
