# Generated by Django 5.0.2 on 2024-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_app', '0012_alter_liked_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
