# Generated by Django 5.0.2 on 2024-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_app', '0014_availabelsize_remove_product_available_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_size',
            field=models.ManyToManyField(blank=True, null=True, related_name='available_sizes', to='apple_app.availabelsize'),
        ),
    ]
