# Generated by Django 5.0.2 on 2024-02-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_app', '0017_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_size',
            field=models.ManyToManyField(related_name='available_sizes', to='apple_app.availabelsize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
