# Generated by Django 5.0.2 on 2024-02-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_is_done_alter_todo_is_reading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='author',
            new_name='user',
        ),
    ]
